SCREEN_W        = 720
SCREEN_H        = 720
CANVAS_W        = SCREEN_W
CANVAS_H        = SCREEN_H
BOARD_W         = CANVAS_W * 0.8
BOARD_H         = CANVAS_H * 0.8
X0              = (CANVAS_W - BOARD_W)/2    # Begin x, y coordinates
Y0              = (CANVAS_H - BOARD_H)/2
XN              = X0 + BOARD_W              # End x,y coordinates
YN              = Y0 + BOARD_H
CELL_W          = BOARD_W/8
CELL_H          = BOARD_H/8
S_R             = SCREEN_W * 0.0075         # Star points radius
B_R             = CELL_W * 0.87             # Bricks radius
FREE            = 0
FREE_CONFIG     = {'fill' : '', 'width' : 0}
BLACK           = 1
BLACK_CONFIG    = {'fill' : 'black', 'width' : 3}
WHITE           = 2
WHITE_CONFIG    = {'fill' : 'white', 'width' : 3}
PLAYER_1        = True
PLAYER_2        = False
HUMAN           = True
AI              = False
